### ISSUE TITLE
Transparency of FLoC features, OT status and Cohort Id

### ISSUE THREAD

**Issue by shigeki** [WICG/floc#113]
Currently, some of the features in FLoC are changed from the default value, such as `kFlocIdMinimumHistoryDomainSizeRequired`  3 to 7. 
Recently, `kFlocPagesWithAdResourcesDefaultIncludedInFlocComputation` was introduced, which is important for users to know what pages are in FLoC calculation.

But users cannot know them unless Google announces their parameters. 
For the transparency of FLoC trials to users, I think it is better to provide an internal page to show the current FLoC feature parameters.

**Comment by michaelkleber** [comment]
Hello Shigeki Ohtsu, the [chromium.org floc page](https://www.chromium.org/Home/chromium-privacy/privacy-sandbox/floc) is intended to be the place where we specify how we are setting each of those parameters for each version of the FLoC clustering algorithm.

So for example, right now the version is "chrome.2.1", and "An individual browser instance's cohort is filtered if the inputs to the cohort id calculation has fewer than seven domain names", i.e. `kFlocIdMinimumHistoryDomainSizeRequired` is 7 as you said.  And a page is included in the "chrome.2.1" calculation if it either uses the document.interestCohort() API is detected as loading ads-related resources, i.e. `kFlocPagesWithAdResourcesDefaultIncludedInFlocComputation` is true.

If we make any changes to these parameters in the future, it will involve changing the version string returned by the API, and we will update that page to say what other behavior we're trying out.

**Comment by shigeki** [comment]
>  we will update that page to say what other behavior we're trying out.

It is great to keep its announcement updated.

But I thought it is more beneficial for users to see and confirm them on their browsers. 
In addition to showing feature parameters, the internal page can show whether FLoC is enabled or not, even when OT is finched to 0.5%. When FLoC is enabled, it can also show its cohort id, and we can also confirm if our cohort id is really changed after a week by looking at it on the page without API. 

Currently, they all can only be achieved by accessing an external page. 
I think its transparency can give users relief to FLoC trials.

**Comment by michaelkleber** [comment]
This is a good point.  We should eventually have a UI to show this, once FLoC is stable.  But @jkarlin was just talking about how we could ship some kind of about:// page with some details of floc-internals, which would help even during the experimental stage where the clustering algorithm is undecided.

**Comment by shigeki** [comment]
Thanks. I've just found the one in chrome://flags/#privacy-sandbox-settings-2 now.
I hope that details are shown on the internal page such as chrome://flock-internals. 
Close this.
