### ISSUE TITLE
API Request

### ISSUE THREAD

**Issue by Rutto17** [WICG/floc#114]
I'm trying to send the cohort to my index.php. Someone can help me?

async function asyncCall() {
    var cohort = await document.interestCohort();
    let url = new URL("https://http.cat/408");
    url.searchParams.append("cohort", cohort);
    creative = await fetch(url);
    console.log(creative);

**Comment by michaelkleber** [comment]
Hi @Rutto17, this question is a good fit for our Dev Rel folks!  Check out this repository to get in touch with them: https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support
