### ISSUE TITLE
What use FloC to calculate ID?

### ISSUE THREAD

**Issue by Rutto17** [WICG/floc#115]
I have just implemented FLoC in my chromium. How is calculated the ID? It use the SimHash algorithm like this:
_Our first approach involves applying a SimHash algorithm to the registrable domains of the sites visited by the user in order to cluster users that visit similar sites together._?

**Comment by michaelkleber** [comment]
This page has many more details about the algorithm we're trying in Chrome:
https://www.chromium.org/Home/chromium-privacy/privacy-sandbox/floc
