### ISSUE TITLE
Cohorts and third-party contexts

### ISSUE THREAD

**Issue by nikoplusx** [WICG/floc#117]
@michaelkleber You closed issue #116 but I do not think your answer was clear. In the link you closed the issue with, it describes the way one can start up his own copy of Chrome with the appropriate flags in order to test the cohorts. So far so good. I have already done this and It works fine. My problem is with [this](https://developer.chrome.com/blog/floc/#third-party-context) part of the documentation you shared. 

In my case I am trying to replicate the behavior of a script loaded by an adtech platform to a publisher's/advertiser's website. In that case one cannot guarantee that the user has the aforementioned flags enabled so I guess I have to follow these instructions - after of course the publisher/advertiser has been appropriately registered.

> You will need to inject the origin trial token in a meta tag in order to test the FLoC API in your code on third-party sites. Origin Trials Guide for Web Developers explains how to do this.

Is this not right? If the cohorts are only working using the aforementioned flags then why are these instructions included here?

**Comment by michaelkleber** [comment]
Hello @nikoplusx,

Chrome's Origin Trial is currently only running for a fraction of people using Chrome Beta.  Most people use Chrome's stable release, where the OT is not yet active.

Please refer to this thread for updates to the OT status: https://groups.google.com/a/chromium.org/g/blink-dev/c/MmijXrmwrJs
