### ISSUE TITLE
how does ad platform choose ads using aggregated information from advertisers

### ISSUE THREAD

**Issue by kzhong130** [WICG/floc#119]
Hi there, I am going through Floc's proposal and very interested in how ad platform should choose ads using aggregated information from advertisers. As far as I can tell, ad platform does not check aggregated information from advertisers. 
That is, for certain advertiser (namely A) who wants its ads to be displayed to users from certain cohort (say cohort 1235). It can report to ad platform that users from cohort 1235 visited my webpage of hiking boots for 100,000 times. If ad platform chooses ads purely based on these aggregated number of visits, it would be highly possible that A's advertisements of hiking boots would be displayed to users from cohort 1235. 
Do you consider this as kind of unfairness that dishonest advertisers would intentionally report incorrect aggregated results? Or is the ad platform's responsibility that it should be able to identify anomalous aggregated information?

**Comment by michaelkleber** [comment]
Hi @kzhong130,

If I understand correctly, you're asking about whether dishonest advertisers might choose to lie about what cohorts they want to show their ads to.  Can you say a little bit more about why they would want to do that?

Advertisers generally pay money to show ads, and the only reason that paying that money is a good idea is because the ads let them make money later.  So deliberately showing ads to "the wrong people" would be an advertiser spending money and not getting anything in return.

**Comment by kzhong130** [comment]
Hi, I am thinking of such scenario: both advertiser **A** and **B** are selling hiking boots and competing with each other. And **A** learns that users from cohort 1235 are highly possible to purchase hiking boots. In order to display its ads, **A** reports aggregated information that cohort 1235 visited my webpage of hiking boots for 100,000 times while **B** only reports honestly with 1,000 visits from cohort 1235.

When ad platform displays ads to users from cohort 1235, it's very likely that it displays ads of hiking boots from advertisers **A** though users from 1235 have no preferences between **A** and **B**. This sounds unfair for **B** as it reports honestly but would lower its chance of ads being displayed? Please let me know how you think about this, thank you!

**Comment by dmarti** [comment]
@kzhong130 In this scenario, who would A and B be reporting this information to? The cohort is only shown to the site that calls `document.interestCohort` and advertisers would be likely to keep this confidential as they do with other customer data today.

**Comment by kzhong130** [comment]
Hi, I see it from [here](https://web.dev/floc/#3.-advertiser:-shoestore.example) that advertisers can `periodically aggregates and shares information about cohorts and product interests with its adtech platform` as I believe ad platform needs these information such that it can recommend ads when publisher requests ads for certain cohort. Thank you!

**Comment by michaelkleber** [comment]
The FLoC cohort is intended to be one signal that can be used by the people who place ads on web pages.  So advertisers, or their agents, who bid in an ad auction can look at the cohort and help them decide how much they want to bid.

So say advertiser *A* claims a lot more hiking boots conversions on cohort 1235.  They tell this information to the DSP who is buying on their behalf.  The DSP calculates that cohort-1235 impressions are worth a lot more to *A* than they are to *B*, and so *A* out-bids *B* for those ad slots.

This is just like any other reason that *A* decides to bid more in the ad auction.  If *A* is over-stating how much value they get from those ads, then they will end up paying too much, which would make *A* sad in all the usual ways — they use up their budget too soon, or get lower return on their ad spend.

**Comment by kzhong130** [comment]
Thank you, that makes a lot more sense!
