### ISSUE TITLE
How to pass extra information back to FLoC?

### ISSUE THREAD

**Issue by og3og** [WICG/floc#120]
After reading the explanation on https://web.dev/floc/#floc-algorithm It mentions that an advertiser site could pass back extra information along with the cohort ID. 

How is this done? I see how to get the cohort ID but how do we pass back information about the user's actions back to the FLoC system? 

The section I was looking at is "The site records that a browser from cohort 1354 showed interest in hiking boots."

Thanks.

**Comment by michaelkleber** [comment]
There is no information passed "back to the FLoC system", in the API we've proposed.  The web.dev article's discussion where "The site records that a browser from cohort 1354 showed interest in hiking boots" is about how an advertiser might choose to _use_ the FLoC cohort information.  We just had a little more discussion on this in #119.

**Comment by og3og** [comment]
Thanks for the response. This makes sense now. 

e.g. An advertiser website would pass the FLoC ID and version back to a DSP for them to enhance their systems to later show ads on that cohort and use the extra information accordingly.
