### ISSUE TITLE
Long Chrome.1.0 IDs

### ISSUE THREAD

**Issue by afung-sharethis** [WICG/floc#127]
Is it normal for chrome.1.0 to have longer IDs than the other versions? Below are some of the IDs we see from chrome.1.0.
```
395497332182609
1078924607911088
688939047155482
43477105904762
137995499423927
1041375465164338
39265881349218
50545240107017
239522867411096
```

**Comment by michaelkleber** [comment]
Anything that says "chrome.1.0" is based on someone starting up Chrome and activating the API with their own collection of command-line flags.  They're not running the actual FLoC algorithm that we've described [here](https://www.chromium.org/Home/chromium-privacy/privacy-sandbox/floc) — in fact really there's no knowing what it means; different people might even have started Chrome up with different flags.

I would recommend ignoring any long IDs and any chrome.1.0 IDs as being meaningless.
