### ISSUE TITLE
Extending FLoC trial period

### ISSUE THREAD

**Issue by captify-mgruau** [WICG/floc#129]
As has previously been discussed, the limitations in proportion of opted-in users and markets mean that it's been hard so far in the trial to capture enough data points to establish a reliable view of the potential of FLoC IDs as input features for behavioural models, or the stability of IDs over time.

If I remember correctly, the current trial is set to conclude on July 15th, and I imagine this date has been chosen for a reason; but is there a chance it can be postponed, if only by a month or so? 
With the news that 3P cookie deprecation has been delayed until late 2023, I would hope there is less rush to move on from this trial and that there is room for more trial time.

**Comment by jkarlin** [comment]
Thanks for raising the concern. The result of the trial is that we need to iterate on FLoC's design and as such have decided not to continue the existing origin trial.
