### ISSUE TITLE
Number of total cohort ids in deployment

### ISSUE THREAD

**Issue by kzhong130** [WICG/floc#136]
Hi there, I am wondering what is the total number of unique cohort ids (i.e., how many unique groups that you are dividing users into) that you are using in real deployment. Or do you have an estimate about what would be a reasonable range of the total number? Thank you!

**Comment by jkarlin** [comment]
Hi kzhong. The number of cohorts used in the experiment was around ~34,000. See the bottom of https://www.chromium.org/Home/chromium-privacy/privacy-sandbox/floc for more details.

**Comment by kzhong130** [comment]
Thank you so much Josh!
