### ISSUE TITLE
Cohorts stability

### ISSUE THREAD

**Issue by cgouvernet** [WICG/floc#26]
FLoC proposal states that the FLoCK will be refreshed as the user traverses the web.

In Issue https://github.com/jkarlin/floc/issues/22, the typical refresh period is said to be once a day.

Advertisers need stability over time for cohort ids in order to learn the affinities of user interests with their products, as shown in the graph below: the cohorts repartition may vary from day to day, but the cohort update should be coherent with previous cohort ids.

What kind of cohort stability FLoC commits to?

![image](https://user-images.githubusercontent.com/69140627/93992284-a6ddef00-fd8d-11ea-9b67-a817348e74cb.png)

**Comment by michaelkleber** [comment]
There are two different types of stability here, so let's be clear about the question:

1. First, there is stability in the _meaning of a flock._  If I the web browsing behavior of the people in flock 43f7 today, I'd like to expect it to be similar to that of flock 43f7 yesterday or last week or last month.

2. Second, there is stability in the _specific people in a flock._  If I'm in flock 43f7 today, then would I still be in that same flock tomorrow or next week?

I think you're asking about Question 1.  We agree that FLoC is only useful if it has pretty good stability in its meaning.  As we run experiments on different clustering techniques, we'll be looking at this important property, though we don't have any data to share yet.

We're also concerned about Question 2 for privacy reasons.  To see why, imagine a person was assigned to a completely random flock, but it changed each day — then it would become an easy cross-site identifier for sites that you visited regularly!  I don't think you need to worry about this question just to use flocks for ad targeting, though.

**Comment by fteverini** [comment]
Hello @michaelkleber do you have a clearer idea on how to deal with meaning of flock stability ? Indeed, if Floc construction changes (for example if the way of vectorizing a Chrome user or the Random Vectors used for SimHash computation change), then new floc ids won't have any relation with previous floc ids, making a previous floc-based targeting obsolete. What is today the privileged solution to this issue ?

**Comment by michaelkleber** [comment]
We added the `document.interestCohort().version` string to the API, which is a label for the flock clustering model that was used.  So if you see the `version` string stay the same, you'll know flock construction still works the same way.

During the Origin Trial we'll probably try multiple version of clustering, even though we'll only have one to start with.  But once the API is launched, we expect to keep the same version for a long time.

**Comment by fteverini** [comment]
Hello @michaelkleber

> 2. Second, there is stability in the _specific people in a flock._  If I'm in flock 43f7 today, then would I still be in that same flock tomorrow or next week?

> We're also concerned about Question 2 for privacy reasons. To see why, imagine a person was assigned to a completely random flock, but it changed each day — then it would become an easy cross-site identifier for sites that you visited regularly! I don't think you need to worry about this question just to use flocks for ad targeting, though.

What is the frequency of update of a floc in the current trial  (and do you have an idea if it will be more or less conserved for the future) ? 
In particular, is there a possibility that the browser floc would be recomputed each time the user goes on a website (so may be several times in the same day) or is it sure that there will be an update only each X days ?

**Comment by michaelkleber** [comment]
For the current trial, we're updating the floc every 7 days.  But everything is subject to change over the course of an Origin Trial, so I can't make any promises about the future.

**Comment by fteverini** [comment]
Thanks @michaelkleber 
I see when testing with floc.glitch.me using `chromium-browser --enable-blink-features=InteresohortAPI --enable-features="FederatedLearningOfCohorts:update_interval/10s/minimum_history_domain_size_required/1,FlocIdSortingLshBasedComputation,InterestCohortFeaturePolicy"` that my floc is quickly updated, I suppose it is due to the `update_interval/10s/`in the command line. Does it mean that anyone may control his floc update ? Or maybe this command line is different from the current trial, and in the trial, a user does not have any control on the floc update interval and the minimum domain size. 

Moreover, when you write 
> For the current trial, we're updating the floc every 7 days.

is the update at the same time for everyone ? Somethink like  : After every sunday at 12pm, at the first time a browser is opened, the floc is updated ?

**Comment by michaelkleber** [comment]
As you guessed, this quick updating is because of that command-line flag.  People who just get FLoC the normal way (controlled by the Chrome origin trial) will see the one-week time interval.

> is the update at the same time for everyone ? Somethink like : After every sunday at 12pm, at the first time a browser is opened, the floc is updated ?

No, everyone updates on their own schedule, approximately 7 days after the previous time they updated.
