### ISSUE TITLE
Test that FLoC cohorts are trained on site content, not accessibility or support for assistive technologies

### ISSUE THREAD

**Issue by dmarti** [WICG/floc#34]
Some sites might plan to use the FLoC cohort as part of a decision to show employment or housing advertising. In order to avoid unlawful discrimination in this situation, cohorts would need to not reflect a disability affecting users who are members of them. 

Sites can vary greatly in both accessibility and in support for assistive technologies. Because the FLoC classifier is machine learning based, it is possible that it could "learn" to identify cohorts based not on site content, but on sets of sites with similar accessibility properties. (For example, an otherwise unrelated set of sites that all happen to have breakage when text is resized in the browser, or terrible screen reader support.)

Is there a way to show that in real world usage FLoC cohorts are not being trained on a11y properties of sites?

### Related issues

 * [This proposal makes false claims about the privacy properties provided by the anonymization techniques used · Issue #6](https://github.com/jkarlin/floc/issues/6)
 * [How to we avoid FLoC replicating algorithmic red-lining and the discriminatory behavioral targeting we've seen in other ML systems? · Issue #16](https://github.com/jkarlin/floc/issues/16)
 * [General concerns about FLoC-powered abuse · Issue #36 · WICG/floc](https://github.com/WICG/floc/issues/36)

**Comment by michaelkleber** [comment]
Take a look at https://www.chromium.org/Home/chromium-privacy/privacy-sandbox/floc, which describes the details of the FLoC calculation algorithm for the first Origin Trial.
