### ISSUE TITLE
floc origin

### ISSUE THREAD

**Issue by fteverini** [WICG/floc#43]
In Floc whitepaper were written 2 main examples of origins from where floc can be derived : 1) user domain encoding, and 2) user pre-existing topics scores, probably inferred from URL text content.
I understand the first encoding is more agnostic than the second one, which relies on an existing human set of categories.
What is today the likeliest path of Floc origin that GChrome will choose, or at least the one that will be chosen for the experiments that will be conducted from March ? 
a) **Domain/URL encoding** without considering text content like the first example of whitepaper 
b) **Word** encoding without considering a human set of categories (remain agnostic)
c) **Topic Category** encoding like in the last example of the whitepaper 
d) Other... ?

**Comment by michaelkleber** [comment]
The FLoC Origin Trial that we expect to run starting in M89 (March 2021) is clustering based only on the top-level domain name of the sites you visit.  No subdomain, no URL, no words, no topics, etc.

We're still exploring the feasibility of more sophisticated signals like the "Topic Category" approach.  If it works, then we will experiment with it at a later time.

**Comment by fteverini** [comment]
Thanks @michaelkleber 
So I guess you confirm that using a mapping of URL (and therefore user) to Topic Categories before hashing still stay in the "spirit" of the Floc even if it is limited and biased towards the categories that would be used (in contrast with Domain/Word approach that would be agnostic).
