### ISSUE TITLE
SortingLSH after SimHash

### ISSUE THREAD

**Issue by fteverini** [WICG/floc#44]
For Floc generation, 

1) Is it planned to use SortingLSH after having applied SimHash, or to map all flocs with too few users to one unique global floc group ?

2) For SortingLSH, I would suggest to not use a lexicographical order but rather an order like  [this](https://github.com/fteverini/SortingLSH/blob/master/sort_binaries_contiguously.py#L8) because lexical order implies to jump from 00111 to 01000 when ordering (in dimension 5), which makes 4 different digits from an element to the following, so very different flocs can be grouped together. In the other hand, another order can be constructed so that **2 consecutive elements have only one different digit**, which would lead to a better cohesion inside a group of gathered flocs.
For example, in dimension  4, it gives an order like that : 0000,0001,0011,0010,0110,0111,0101,0100,1100,1101,1111,1110,1010,1011,1001,1000

**Comment by michaelkleber** [comment]
Hello @fteverini,

1. We're using SimHash to map a browsing history to a bitstring, and then SortingLSH to cluster those bitstrings together into large enough flocks.  A flock with too few people in it will just get dropped — we will report no flock for those people.

2. The SortingLSH will always cluster together a group of people whose SimHash bitstrings begin with the same k-bit prefix, for some value of k.  (We're referring to this as a "PrefixLSH".)  This isn't obvious from the code in Chrome; instead it's a property of the SortingLSH cluster sizes sent to the browser.  But your observation about lexical order is exactly the reason we're doing it this way.

**Comment by jonasz** [comment]
> We're using SimHash to map a browsing history to a bitstring

I was wondering, do you plan to expose this bitstring (or the common prefix, after PrefixLSH is applied) as the cohort id? (This would have interesting implications on interpretation of cohort ids, and comparisons of cohort ids.)

**Comment by fteverini** [comment]
Thanks @michaelkleber 

But by construction I understand that all people should have a flock because if a bitstring "contains" too few users, you ascend to its father and continue ascending until you find a node with at least k users (k of k-anonymity).

If I understand well, for most bitstrings, we should have the equality bitstring==flock, and only rare bitstrings of very few users will need to be gathered (eventually with bitstrings with many users, will depend on the position in the tree).

**Comment by michaelkleber** [comment]
@jonasz: The FLoC API is not going to expose the bitstring, just a flock number from 1 to N.  The fact that there is an underlying bitstring is an implementation detail, and we're still experimenting with different ways to do clustering... so a future clustering algorithm might not go through a SimHash stage at all!

@fteverini:

> But by construction I understand that all people should have a flock because if a bitstring "contains" too few users, you ascend to its father and continue ascending until you find a node with at least k users (k of k-anonymity).

This isn't quite right — for example, the number of people who fall into a given flock may change over time, as we re-compute, but we don't want to renumber all the flocks when that happens!  So it's certainly possible that we'll calculate a flock assignment and then decide to drop it.

> If I understand well, for most bitstrings, we should have the equality bitstring==flock, and only rare bitstrings of very few users will need to be gathered (eventually with bitstrings with many users, will depend on the position in the tree).

In our initial experimental implementation, we're calculating a 50-bit SimHash and then truncating it appropriately — I'd expect the prefix for a flock to almost always be fewer than 50 bits.

**Comment by fteverini** [comment]
Yes I was still with the idea of 16-bit mentioned somewhere, but sure, with 50 bits, it's different...
Thanks @michaelkleber

**Comment by fteverini** [comment]
1. @michaelkleber for a given k-anonymity of k, suppose you have a prefix **11010**1 which contains more than k users, and his brother  **11010**0  contains less than k users, do you choose **11010**1 to be the floc,  and drops all users whose hash is prefixed by **11010**0, or do you ride up to the node above it, choosing **11010** as floc (and not **11010**1), in order to cover more users even if it is less precise ?
2. I understand that flocs are not renumbered frequently in order to keep ads campaigns sustainable. But from what you say I also understand that, more frequently, number of users in each floc are recomputed, to drop flocs which happen to have too few users now. At which frequency are these nb of users by floc recomputed ?
3. Can a floc be eliminated one day and come back  another day because it now contains enough users ?
Thanks @michaelkleber
