### ISSUE TITLE
Training based on FQDN or registerable domain?

### ISSUE THREAD

**Issue by dmarti** [WICG/floc#50]
The README says, 

> Our first approach involves applying a SimHash algorithm to the domains of the sites visited by the user in order to cluster users that visit similar sites together.

Will this be the FQDN or the registerable domain?  (Will store.example.com, support.example.com, www.example.com all be counted separately or all included under example.com?)

**Comment by jkarlin** [comment]
Registrable domain, so they'd all be included under example.com.

**Comment by jkarlin** [comment]
Updated in 18e1374c0fb658f209e633145a74c9374ca89545.
