### ISSUE TITLE
Granular vs Similar flocks

### ISSUE THREAD

**Issue by ablanchard1138** [WICG/floc#53]
Hello, 

Not sure this has been mentioned already, apologies if it is the case. 

Should we expect groups of people to be partitioned in as many flocks as possible (up to the limit of eligibility) or up till there is enough similarity between them?

For the sake of the example, let us say that a flock minimum size will be 1 000. Now, if you have 2 000 000 people visiting one and only one website (website.example), will they be splitted into 2 000 differents flocks with 2 000 different flock_id, or will they be in the same big flock with the same flock_id?

The two cases have definitely different pros and cons...

The 'similar enough' flocks will lead to bigger groups, but also mean that it is going to be easier to reverse engineer a flock and then a full population that a malevolent party could try to influence one way or another (one could go to a website or engage in a particular browsing, observe flock_id, and use it to target all people doing the same thing, or physically extract flock_id from devices during investigations etc). 

The 'granular' flock could be seen as too granular and crossed with other features could de facto become an identifier, but at least is more robust to any attacks as suggested above. It could also reassure publishers that FLoC does not consist in a 'leakage' of their contextual data.

**Comment by michaelkleber** [comment]
For the first FLoC experiment:

- We're not subdividing flocks randomly, only based on similarity.
- We're only looking at people who have at least three different sites in their browsing history.

Certainly someone could figure out the answer to "what flock will people have if the only three sites they visited were A.com, B.com, and C.com?"  But there will be people in that flock who visited other combinations of sites as well.

**Comment by michaelkleber** [comment]
For the first Origin Trial implementation of flock clustering, we're only using the set of domains a person visited during the computation window (the past week).  I'm not sure what the ".........." in your example stands for, but if it's just talking about waiting a while, then all four of your browsing behaviors would lead to the same flock.

Of course you might wonder if treating these browsing histories as different would lead to a more useful way of clustering, and perhaps it would.  We expect to explore different approaches here.

I agree that _examples like 'car enthusiasts' etc_ might be plausible for some ways of doing clustering and implausible for others.  These sorts of labels would not be part of the FLoC API; it would be up to publishers, advertisers, and ad networks to observe behavior and figure out what a flock means.

**Comment by ablanchard1138** [comment]
thank you Michael, that is much clearer for me now!
