### ISSUE TITLE
Getting Floc Cohort in Chrome 89

### ISSUE THREAD

**Issue by afung-sharethis** [WICG/floc#56]
Is it possible to get the Floc Cohort in Chrome 89? I called document.interestCohort() using Chrome 89 with Privacy Sandbox Enabled, but I got the error below.

```f.htm:3 Uncaught TypeError: document.interestCohort is not a function```

**Comment by xyaoinum** [comment]
The API is behind an Origin Trial that hasn't started yet. Technically things may change between now and then so I'd wait for the official rollout.

In case you absolutely want to test it locally, you can try the steps and flags mentioned https://bugs.chromium.org/p/chromium/issues/detail?id=1175637#c5

**Comment by afung-sharethis** [comment]
@xyaoinum - Do you know approximately when the origin trial will begin?
