### ISSUE TITLE
What access with chrome extensions have to read/overwrite FLoCs?

### ISSUE THREAD

**Issue by brodrigu** [WICG/floc#61]
What access to the FLoC APIs will chrome extensions have?

Can a browser extension read a user FLoC?

Can a browser extension overwrite a users FLoC?

**Comment by brodrigu** [comment]
This seems to be related to issue #17. Though not technically a duplicate.

**Comment by jkarlin** [comment]
A browser extension can inject javascript into pages that the user visits and therefore read the value. An extension could also overwrite the document.interestCohort() API and return a different value.

**Comment by brodrigu** [comment]
Thanks for clarifying Josh.
