### ISSUE TITLE
Access to FLoC IDs During Origin Trial

### ISSUE THREAD

**Issue by afung-sharethis** [WICG/floc#63]
Approximately when will the origin trial for FLoC begin? During the trial, what will a publisher be able to test? For example, will the publisher be able to access the FLoC IDs of all their users or will it only be possible to get FLoC IDs from other Chrome 89 browsers?

**Comment by michaelkleber** [comment]
> Approximately when will the origin trial for FLoC begin?

We're working on getting it started now.  It will be live sometime later in M89, but we don't have an exact date.

> During the trial, what will a publisher be able to test? For example, will the publisher be able to access the FLoC IDs of all their users or will it only be possible to get FLoC IDs from other Chrome 89 browsers?

The origin trial will only be active in Chrome M89.  Also it will only be active for some percentage of people, probably initially 5%.
