### ISSUE TITLE
Will the FLoC origin trial support third-party tokens?

### ISSUE THREAD

**Issue by dmarti** [WICG/floc#64]
Some Chrome origin trials allow for "Third-party matching. The token will be injected by script on other origins." ([example:Trust Tokens origin trial](https://developer.chrome.com/origintrials/#/register_trial/2479231594867458049)) and others do not. ( [example: AppCache Origin Trial](https://developer.chrome.com/origintrials/#/register_trial/1776670052997660673))

Will the FLoC origin trial allow for the token to be added by creating and injecting a <meta> tag into the head of pages on additional domains other than the domain originally used for registration?

Reference: [Origin Trials Guide for Web Developers | OriginTrials](https://googlechrome.github.io/OriginTrials/developer-guide.html)

**Comment by michaelkleber** [comment]
Yes!  Indeed, the FLoC Origin Trial would be essentially useless if it were not the third-party type.

**Comment by dmarti** [comment]
Thank you, this is helpful.
