### ISSUE TITLE
User transparency and control over FLOC

### ISSUE THREAD

**Issue by jdelhommeau** [WICG/floc#65]
My understanding of FLOC is that based on his browsing history, a user will be assigned to a FLOC, represented by a FLOC ID, with no further description.
As such, the user will be assigned to a cluster of users, but without any understanding of what that group is or how it is perceived by websites he visits.

On the other hand, publishers and adtech vendors with a large set of first party data will be able to identify some taxonomy to add on top of a given FLOC id. For example, determine that people in FLOC id X32 are more likely to like travels and do sports. And as such, those publishers / vendors will try to deliver the user with sport / travels related ads.

It feels that as a user, I will lack transparency and control over my FLOC, whereas, third party company might be able to have much more transparency over it.

Was it ever considered to assign users not to a single, user-meaningless FLOC id, but rather have the browser assign the user to a set of clearly defined categories ("sport", "travel", etc.), which the user could easily access in his browser, manually add himself / remove himself from categories, etc. instead of the current system?

From a user's point of view, I would feel much more in control to know what categories I belong to and ability to edit them, and how vendors might perceive me, vs being assigned to cluster that I don't know how people will interpret.

**Comment by michaelkleber** [comment]
The first version of FLoC clustering that Chrome plans to experiment with is based just on the list of domains you've visited.

We do indeed intend to explore other approaches, including the browser "understanding" web pages enough to assign them to topic categories.  Since we still don't want to send any data to any server, all of the machine learning involved in this understanding would need to happen inside the browser — so it's not yet clear whether this is going to be feasible.  But as you point out, it would have some nice explainability benefits, if it were to work.

The browser would still need to perform something similar to FLoC's clustering and k-anonymity checking, though.  Even if you've hand-curated the list of categories yourself, if you happened to choose a list that's different from anyone else, it will be used to track you.

**Comment by jdelhommeau** [comment]
Thank you @michaelkleber , the FLoC's clustering and k-anonymity checking definitely make sense.
So in the future, the idea is for FLoC to expose not just a single FLoC ID, but rather a list of identified topics (sport, travel, etc.), that user will be able to see and control, and which vendors will be able to use to deliver cohort level audience targeted ad, without having to train machine learning algorithms to establish some FloC meaning. Correct?

Rather than having the browser learn which categories to associate with a given domain, couldn't a publisher provide that information himself for his website, using some meta header? They would be able to add meta-header for every standardized categories (the IAB techlab just released some standardized list for this effect: https://iabtechlab.com/wp-content/uploads/2021/03/IABTechLab_Taxonomy_and_Data_Transparency_Standards_to_Support_Seller-defined_Audience_and_Context_Signaling_2021-03.pdf)

**Comment by michaelkleber** [comment]
Hi Julien,

Even in a possible future where we have an implementation of FLoC clustering that is based on topics, we do not plan to change what is exposed to a server.  FLoC is a JavaScript API that could have many possible implementations of how clustering works.

But certainly a server could interpret the flock in different ways; some people could use an ML algorithm, while others could look it up on some list of IAB categories.

In a categories-based-FLoC world, publishers providing metadata about their pages certainly could be an input.  Of course someone still needs to do the work labeling pages with topics.  There would be lots of work to do there — it's not obvious why the system would incentivize those labels being _accurate_.

**Comment by jdelhommeau** [comment]
Thank you, just to confirm:

>we do not plan to change what is exposed to a server

This means that FLOC will continue to expose a single FLOC ID, with no descriptive meaning (through the `document.interestCohort()` method) eventhough, the FLOC could then be displayed to the user as descriptive categories. Correct?

Any reason why to not provide the full list of categories through the `document.interestCohort()` ? If the user has control over it, and agrees to share those information, there should be no reason to hide those. Especially since in doing so, we may end up with initial problem, which is that adtech vendors will inaccurately interpret the FLOC, not respecting user's categories of interest choices.

> In a categories-based-FLoC world, publishers providing metadata about their pages certainly could be an input. Of course someone still needs to do the work labeling pages with topics. There would be lots of work to do there — it's not obvious why the system would incentivize those labels being accurate.

Agree that pub may have incentive to label their site into "valuable" categories, to orien the FLOC categories assign to their audience and inflate their inventory value, so may not be a good solution

**Comment by michaelkleber** [comment]
> This means that FLOC will continue to expose a single FLOC ID, with no descriptive meaning (through the `document.interestCohort()` method) eventhough, the FLOC could then be displayed to the user as descriptive categories.

Yes, that's right.

> Any reason why to not provide the full list of categories through the `document.interestCohort()` ?

Chrome might try out an `interestCohort()` based on categories, but we wouldn't want to decide, once and for all, that any browser that implements `interestCohort()` in the future must do so based on categories.  The API surface is a forward-looking promise.

**Comment by jdelhommeau** [comment]
Thank you @michaelkleber .

I understand your point about wanting to have a forward-looking promise.
However, if the API keeps returning a non descriptive FLOC ID, we will not solve for the second part of the issue, which is that user will have no control how vendors / publishers will perceive him, since those vendors / publishers will still need to build some algorithm to identify interest behind a FLOC ID, and be wrong about it.
So a user could have indicated in his browser not to be interested by travel ad for example, and yet, will keep seeing travel ads because vendors will have a wrong interpretation of the FLOC id.
Or am I misunderstanding how you are thinking about a categories based FLOC solution?

**Comment by michaelkleber** [comment]
That's right, we're not trying to build a way for a person to specify what ad topics they want to see.  Even if we did build that, ad tech companies would still make whatever decisions they feel like about what ads to show — I don't see any way for the browser to never be in a position to tell some "if you un-check this checkbox then you won't see any more travel ads."

**Comment by jdelhommeau** [comment]
True. But by not providing user's choice to vendors, the scenario of user seeing non relevant ad is much more likely I think.

> we're not trying to build a way for a person to specify what ad topics they want to see

Is there a specific reason for that? Wouldn't that solve for the problem FLOC is trying to solve (audience targeting) while removing the error factor in decoding FLOC meaning on the vendors side? I understand this is an important change and that FLOC is well advanced already, but just curious, regardless of the state of the implementation of current solution, is there a reason to privilege a non descriptive FLOC ID over a standardized set of descriptive categories? I am genuinely asking.

**Comment by michaelkleber** [comment]
First, the kind of clustering that we do in FLoC would still be necessary even if the underlying data is a person's expressed preferences — otherwise a person who expresses a unique or low-cardinality set of interests could be tracked as a result.

Second, ad tech companies who saw a person express interests in categories A,B,C could still use that information to show them ads about D.

So I don't think the "list of categories" alternative actually solves either of the really hard problems with FLoC.

**Comment by jdelhommeau** [comment]
I agree none are ideal solutions.

> the kind of clustering that we do in FLoC would still be necessary even if the underlying data is a person's expressed preferences

Yes definitely agree here.

> Second, ad tech companies who saw a person express interests in categories A,B,C could still use that information to show them ads about D.

True, but at least it would avoid all the misinterpretation errors.

I am just curious if there would be any privacy concern with that interest category solution. Another benefit for adtech vendors is that it removes lot of the work they will need to do to identify FLoC meaning vs current solution.

Was the interest category solution ever envisaged ? What were pros and cons of the two approach?
