### ISSUE TITLE
participating in Origin Trial for FLOC in EMEA, eprivacy and GDPR concerns

### ISSUE THREAD

**Issue by jdelhommeau** [WICG/floc#66]
As FLOC Origin trial is about to start, I am curious if any vendor (including Google) has any intention to run tests in EMEA region, where ePrivacy and GDPR laws may apply.

If so, as a vendor accessing FLOC (who likely falls under ePrivacy tracker definition and as well under personal data definition in some cases), what work have you done to comply with those laws? I believe the concerns were well described in this previous issue: https://github.com/WICG/floc/issues/18

@michaelkleber, can you or someone at Google Ad provide any details on this ? Is Google Ad going to support any test of FLOC in EMEA where ePrivacy / GDPR apply during the initial Origin trial of FLOC? If so, can you share Google's position on this? Will Google Ad only process FLOC if they have consent to access trackers? On what legal base, and for what purposes will Google Ad process FLOC ?

**Comment by michaelkleber** [comment]
(As discussed in this morning's Web Advertising Business Group:)

The initial Chrome Origin Trial will only be enabled for a fraction of traffic, and only in some countries and not others.  At the outset, it won't be enabled for users who are located in the EEA or the UK.

**Comment by jdelhommeau** [comment]
Thank you @michaelkleber !
Quick follow up question on this topic. Will opening Trial be available in California where CCPA apply? I am not as close to the CCPA topic as I am with ePrivacy / GDPR, but I imagine there could be similar consideration in running FLoC Opening Trial in California as well.

**Comment by michaelkleber** [comment]
The initial Chrome Origin Trial will only be enabled for a fraction of traffic, and only in some countries and not others.  At the outset, it will be available in the US.
