### ISSUE TITLE
Local FLoC data location and sync

### ISSUE THREAD

**Issue by gitgitwhat** [WICG/floc#68]
Where will FLoC data be stored locally?  I see my Chrome profile has a FloC file folder but it is empty a the moment.  Because it is all supposed to be stored locally, does deleting the local data (where ever it may reside) reset all of my cohorts?  Or will there a sync mechanism (such as the Google account) that saves calculated cohorts?

**Comment by michaelkleber** [comment]
The only stored data about _your_ behavior is your browsing history, which is stored in the same place it always was.  See chrome://history for a way to interact with it.  Clearing any of the data within the 7-day calculation window does indeed reset your flock.
