### ISSUE TITLE
Details of regions excluded from origin trials

### ISSUE THREAD

**Issue by michaljaron** [WICG/floc#80]
Hello!
In accordance with #66 and latest media reports, due to the GDPR regulation, EEA countries, are courrently excluded from origin trials. Can you ellaborate more on this topic? 

- Is there any list of excluded countries available?
- Exclusion is made based on domain's country of registration or location of user activity, or based on any other feature?
- Are there any expectations about date of origin trails start for EEA and UK?

**Comment by michaelkleber** [comment]
All the information available is already in #66.  In particular, as I said on that issue, things are controlled by where the user is located.  When we have a list of countries, I'll post that there as well.
