### ISSUE TITLE
Access to FLoC IDs: Restricting to fenced frames & trusted servers? 

### ISSUE THREAD

**Issue by garjoh** [WICG/floc#81]
The FLoC proposal has received criticism--rightly or wrongly--for exposing FLoC IDs to websites and advertisers. One possible solution here would be to treat FLoC IDs like interests groups in TURTLEDOVE/FLEDGE. That is, FLoC IDs have several privacy considerations built in, but could further mitigate privacy concerns if the cohort IDs are not exposed to advertisers & websites. In particular, FLoC IDs could be contained within fenced frames (TURTLEDOVE) and advertisers could load their bids on to a truster server (FLEDGE/DOVEKEY). 

This suggestion grew out of my conversation with CafeMedia's Don Marti on twitter: https://twitter.com/garjoh_canuck/status/1372580392918790146?s=20

**Comment by michaelkleber** [comment]
We did indeed consider this idea — check out the mention of [FLoC in the original TURTLEDOVE explainer](https://github.com/WICG/turtledove/blob/main/Original-TURTLEDOVE.md#floc).

Obviously keeping it as a signal that can be used alongside contextual information makes FLoC much easier to adopt.  The targeting use case is of course easier when it can be used in server-side auctions that ad tech is already used to, and the "understand what a flock's behavior is" problem would be harder with only aggregate data.

Several of the proposals discussed in the WebAdv BG over the past year have tried to combine these two ideas, with on-device behavior models leading to interest group membership; see e.g. Magnite's [Proprietary Cohorts TURTLEDOVE-style](https://github.com/MagniteEngineering/ProprietaryCohorts/blob/main/TURTLEDOVE-style.md) from @brodrigu or 1plusX's [SWAN](https://github.com/1plusX/swan) from @WICG/controls-list 

So on-device-only BYO-FLoC-model interest groups is certainly a possible direction for future work.  But for ease of use and rapid evaluation of this new idea, flocks joinable to context have substantial advantages.

**Comment by garjoh** [comment]
Thanks for your quick response, Michael. I missed that you had mentioned this beforehand and I see the rationale for ordering the roll-out as you have.

**Comment by TheMaskMaker** [comment]
I think there would certainly be concerns about hiding floc ids from the website as well as the advertisers. First, it would have to be made 100% inaccessible to all parties in the industry, or someone would have it and then have complete control over the data which would put users, and really everyone in a worse position. Assuming it can be made 100% inaccessible, it could also make validation very difficult. Might be getting ahead of the horse though so first let me ask:

@michaelkleber is this on the floc roadmap and is it in this current proposal or is this for a future WICG group? Or is this something chrome might roll out as an update to floc later on without a working group should this iteration pass?
