### ISSUE TITLE
FLoC OT - 0.5% of Chrome page loads limit

### ISSUE THREAD

**Issue by lbdvt** [WICG/floc#83]
Hi,

The FLoC Origin Trial is now open, congrats for reaching this milestone.

Chrome Origin Trials include a usage limit, as described in https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md#19-are-there-any-usage-limits-on-experimental-features .

This explainer states:
> [large production sites] must take care to limit usage to a suitable portion of their traffic

Regarding the FLoC OT, does Chrome expect each Ad Tech Provider to limit its volume of FLoC API queries to 0.5% of eligible traffic?

**Comment by michaelkleber** [comment]
Hello!  Thank you, we're happy to be here.

> Regarding the FLoC OT, does Chrome expect each Ad Tech Provider to limit its volume of FLoC API queries to 0.5% of eligible traffic?

No, we are taking care of this using Chrome's field trial infrastructure.  Ad Tech Providers participating in the Origin Trial can just try to use the interestCohort() API.  The API will only exist for a small fraction of browser instances, which will ensure that the overall usage remains below the Origin Trial limit.
