### ISSUE TITLE
Wording error in https://wicg.github.io/floc

### ISSUE THREAD

**Issue by lbdvt** [WICG/floc#84]
Hi,

There seems to be a wording error in https://wicg.github.io/floc/#interest-cohort-section, I guess that:

> The InterestCohort dictionary is used to contain the string representation of the interest cohort id and the string representation of the interest cohort id.

should be:

> The InterestCohort dictionary is used to contain the string representation of the interest cohort id and the string representation of the interest cohort **version**.

(Sorry, didn't find how to do a pull request for that).

**Comment by michaelkleber** [comment]
Yup, oops.  @xyaoinum

**Comment by xyaoinum** [comment]
The wording error should be fixed now. Thanks for pointing this out.
