### ISSUE TITLE
Estimating FLoC sizes and insights

### ISSUE THREAD

**Issue by keyo321** [WICG/floc#87]
Hi,

Thank you for hosting the FLoC call today.   In the meeting, Michael Kleber mentioned chrome does not provide counts for FLoC sizes, however, wouldn't entities with a large web footprint be able to accomplish this?  SSPs for example are observing billions of daily bid impression data across the web, and theoretically, they could have a very clear picture of all the FLoC ID sizes and their respective browsing patterns.  

thanks,

**Comment by michaelkleber** [comment]
We certainly expect people to try to get a picture of different flocks' respective browsing patterns.

The size of a flock is trickier.  Certainly you can count the number of people you have observed in each flock.  But you wouldn't know how many people are in the flock whom you _haven't_ observed, and the browser doesn't offer anything to help you estimate how many people that might be.

**Comment by TheMaskMaker** [comment]
@michaelkleber You mentioned something very interesting, how would you count the observed people in each floc? Is this with first party cookies identifiers, or is there another way?
