### ISSUE TITLE
Multiple tokens on a page

### ISSUE THREAD

**Issue by dmarti** [WICG/floc#88]
If more than one script on a page adds an origin trial meta element, is the page enrolled in the origin trial as long as at least one meta element has a valid token in it? Thank you.

**Comment by michaelkleber** [comment]
That's correct.  See the [Origin Trials developers guide FAQ](https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md#15-can-i-provide-multiple-tokens-on-a-page).
