### ISSUE TITLE
Meaning of FLoC ID Over Time

### ISSUE THREAD

**Issue by afung-sharethis** [WICG/floc#89]
In the floc call today, it was stated that the meaning of the floc ID stays the same over time. Assuming that we are using the simhash method, is this true? For example, let's say that the IDs were calculated when only domains a.com and b.com existed. Then, a.com and b.com disappear. Later, c.com and d.com appear. When the IDs are calculated with these domains, wouldn't it be possible for the meaning of the IDs to change, given that the content in domains a.com and b.com is completely different from the content in domains c.com and d.com?

**Comment by michaelkleber** [comment]
Yes, you're correct: the _definition_ of a cohort stays the same over time, but if the behavior of actual people changes (e.g. by some sites becoming more or less popular), then the _meaning_ of a cohort could change as a result of changes to the web browsing habits of people at large.
