### ISSUE TITLE
Versions of FLoC used during the origin trial?

### ISSUE THREAD

**Issue by dmarti** [WICG/floc#94]
The version covered here: [FLoC Origin Trial & Clustering - The Chromium Projects](https://www.chromium.org/Home/chromium-privacy/privacy-sandbox/floc) is "chrome.2.1"

One user of the https://floc.glitch.me/ demo has mentioned seeing a version "chrome.1.1" -- which versions are going to be active during the origin trial?

**Comment by michaelkleber** [comment]
See my reply https://github.com/WICG/floc/issues/90#issuecomment-814379729
