### ISSUE TITLE
Can you fuck off from users' privacy?

### ISSUE THREAD

**Issue by PELock** [WICG/floc#99]
Seriously. To hell with your tracking technology.

**Comment by michaelkleber** [comment]
Hi Bartosz,

First, FLoC is not useful for tracking.  There are thousands of people with the same FLoC, so someone trying to use it to track you would end up seeing a huge amount of not-you mixed in with a very small amount of you.

Second, FLoC is all about getting rid of third-party cookies — which _are_ a widely-used tracking tool.  Unfortunately, if we just get rid of the cookies without anything else to support some key cookie use cases, then most of the web sites in the world would lose something like 50%-70% of their revenue.

So FLoC is one part of a larger plan that keeps the web working well even when nobody can track anymore.

**Comment by PELock** [comment]
How about we don't use it at all? Vivaldi browser dumped this idea and won't use it.

**Comment by CounterPillow** [comment]
> then most of the web sites in the world would lose something like 50%-70% of their revenue.

good.

**Comment by PELock** [comment]
Your unrealistic and corporational view of the world through the advertisement lenses is the problem.

Most ppl use ad blockers. Get real. Even my grandma uses uBlock Origin.

**Comment by PELock** [comment]
I will gladly publish a plugin to block it, If it's not already available.

Here's one fuck off
https://www.searchenginejournal.com/duckduckgo-announces-plans-to-block-googles-floc/401993/

Here's a second fuck off
https://vivaldi.com/blog/no-google-vivaldi-users-will-not-get-floced/

And here's the final fuck off from Mozilla, Apple & Microsoft to your bullshit technology
https://www.theverge.com/2021/4/16/22387492/google-floc-ad-tech-privacy-browsers-brave-vivaldi-edge-mozilla-chrome-safari

So here you go and fuck off.

**Comment by yoavweiss** [comment]
This issue is in violation of the [W3C CEPC](https://www.w3.org/Consortium/cepc/) and I'm deleting it. 
@PELock - please consider this an official warning.
